name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:  
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            pip install -r requirements.txt

        - name: Train model
          run: python src/train.py

        - name: Build docker image
          run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .

        - name: Login to GHCR
          uses: docker/login-action@v3
          with: 
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Push image
          run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}

        - name: Collect metrics
          id: metrics
          run: |
            echo "V01_RMSE=0.123" >> $GITHUB_OUTPUT
            echo "V02_RMSE=0.110" >> $GITHUB_OUTPUT

        - name: Set version output
          id: version
          run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

        - name: Create Release Notes
          run: |
            cat > release_notes.md << EOF
            # Release ${{ github.ref_name }}
            
            | Version | Model | RMSE |
            |---------|-------|------|
            | v0.1 | LinearRegression | ${{ steps.metrics.outputs.V01_RMSE }} |
            | v0.2 | RandomForestRegressor | ${{ steps.metrics.outputs.V02_RMSE }} |
            
            Pull the image:
            \`\`\`bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            \`\`\`

            Run the container:
            \`\`\`bash
            docker run -d -p 9696:9696 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            \`\`\`

            Health check:
            \`\`\`bash
            curl http://localhost:9696/health
            \`\`\`

            Prediction:
            \`\`\`bash
            curl -X POST http://localhost:9696/predict \\
              -H "Content-Type: application/json" \\
              -d '{"age": 0.02, "sex": -0.044, "bmi": 0.06, "bp": -0.03, "s1": -0.02, "s2": 0.03, "s3": -0.02, "s4": 0.02, "s5": 0.02, "s6": -0.001}'
            \`\`\`

            See [CHANGELOG.md](./CHANGELOG.md) for detailed changes.
            EOF

        - name: Publish release
          uses: softprops/action-gh-release@v2
          with:
            body_path: release_notes.md
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}